import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CM_HOME } from "../../core/config.js";
import { daemonEntry } from "../common.js";

export const WRAPPER_PATH = join(CM_HOME, "bin", "cm-daemon");

/**
 * A tiny launcher the service manager runs instead of a baked-in node path, so a Node upgrade (nvm, brew)
 * does not break the service: it re-resolves `node` from a sane PATH at every start.
 */
export function writeWrapper(): string {
  const { cmd, args } = daemonEntry();
  const isNode = cmd === process.execPath;
  const nodeDir = cmd.replace(/\/[^/]+$/, "");
  const script = `#!/bin/sh
# claudemanager daemon launcher (generated by \`cm daemon install-service\`)
export PATH="${nodeDir}:$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
${isNode ? `NODE="$(command -v node || echo "${cmd}")"\nexec "$NODE" --max-old-space-size=4096 ${args.map((a) => `"${a}"`).join(" ")}` : `exec "${cmd}" ${args.map((a) => `"${a}"`).join(" ")}`}
`;
  mkdirSync(join(CM_HOME, "bin"), { recursive: true, mode: 0o700 });
  writeFileSync(WRAPPER_PATH, script);
  chmodSync(WRAPPER_PATH, 0o755);
  return WRAPPER_PATH;
}
